service: notification-service

frameworkVersion: '^3.34.0'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - ${file(iam/SendMailIAM.yml):SendMailIAM}
        - ${file(iam/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.MailQueue.arn}
          batchSize: 1 # Default batchSize is 10

custom:
  MailQueue:
    name: MailQueue-${self:provider.stage}
    arn:
      Fn::GetAtt: [MailQueue, Arn]
    url:
      Ref: MailQueue
